name: Build

on:
  push:
    branches:
      - master

jobs:
  Windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache file
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            %APPDATA%\npm-cache
            %LOCALAPPDATA%\electron\Cache
            %LOCALAPPDATA%\electron-builder\Cache
          key: ${{ runner.os }}-build-caches-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Install Dependencies
        run: npm install

      - name: Build src code
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.access_token }}

      - name: Release package
        run: |
          npm run publish:win:setup:x64:always
          npm run publish:win:setup:x86
          npm run publish:win:setup:arm64
          npm run publish:win:setup:x86_64
          npm run publish:win:7z:x64
          npm run publish:win:7z:x86
          npm run publish:win:7z:arm64
        env:
          GITHUB_TOKEN: ${{ secrets.access_token }}
